# Generated by Django 3.0.14 on 2021-08-17 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='DJ XYZ', max_length=250)),
                ('tipo', models.CharField(default='disjuntor', max_length=250)),
                ('modelo', models.CharField(default='modelo-a', max_length=250)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='SE XYZ', max_length=250)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fim', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='mdj.Equipamento')),
            ],
            options={
                'ordering': ('inicio',),
            },
        ),
        migrations.AddField(
            model_name='equipamento',
            name='localidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamento', to='mdj.Localidade'),
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('nome', models.CharField(default='agente-1', max_length=250)),
                ('tipo', models.CharField(choices=[('raspberry-pi-model-b', 'Raspberry-Pi-Model-B')], default='raspberry-pi-model-b', max_length=250)),
                ('localidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agente', to='mdj.Localidade')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
    ]
