# Generated by Django 3.0.14 on 2021-07-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('tipo', models.CharField(choices=[('raspberry-pi-model-b', 'Raspberry-Pi-Model-B')], default='raspberry-pi-model-b', max_length=250)),
            ],
            options={
                'ordering': ('endereco_ip',),
            },
        ),
    ]
