# Generated by Django 3.0.14 on 2021-08-17 00:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mdj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fim',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 0, 14, 24, 429965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='inicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 0, 14, 24, 429937, tzinfo=utc)),
        ),
    ]
